name: pr-deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy PR environment
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 16
      stage: pr${{ github.event.number }}
      AWS_DEFAULT_REGION: us-east-1
      environment: pr
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
