name: pr-remove

on:
  pull_request:
    types: [closed]

jobs:
  sls-pr-remove:
    name: Remove PR environment
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      stage: pr${{ github.event.number }}
      working-directory: ./
      AWS_DEFAULT_REGION: us-east-1
      environment: pr
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
